image: node:16

pipelines:
  default:
    - step:
        name: build
        caches:
          - node
        script:
          - yarn
          - yarn test
  tags:
    v*:
      - step:
          name: publish module
          deployment: production
          script:
            - yarn
            - yarn build
            - pipe: atlassian/npm-publish:0.2.0
              variables:
                NPM_TOKEN: $NPM_TOKEN
